version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    time: "00:00"
    timezone: Europe/Stockholm
  open-pull-requests-limit: 99
  target-branch: dev
  ignore:
  - dependency-name: husky
    versions:
    - 5.0.9
    - 5.1.0
    - 5.1.1
    - 5.1.3
    - 5.2.0
  - dependency-name: semantic-release
    versions:
    - 17.3.9
    - 17.4.0
    - 17.4.1
  - dependency-name: "@commitlint/config-conventional"
    versions:
    - 12.0.1
  - dependency-name: "@commitlint/cli"
    versions:
    - 12.0.1
  - dependency-name: keytar
    versions:
    - 7.4.0
  - dependency-name: commander
    versions:
    - 7.0.0
    - 7.1.0
